name: CLImobile
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#396599'
    - '#000000'
    - '#ffffff'
    - '#e99622'
    - '#0000ff'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
